# Generated by Django 4.2.6 on 2023-11-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDictionaryProperty',
            fields=[
                ('RecID', models.AutoField(primary_key=True, serialize=False)),
                ('RecSymbols', models.CharField(max_length=10)),
                ('RecDescr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CRock',
            fields=[
                ('RecID', models.AutoField(primary_key=True, serialize=False)),
                ('RecWellID', models.IntegerField(default=-1)),
                ('RecTop', models.FloatField(default=-1)),
                ('RecBottom', models.FloatField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='CWell',
            fields=[
                ('RecID', models.AutoField(primary_key=True, serialize=False)),
                ('RecCountry', models.CharField(max_length=50)),
                ('RecRegion', models.CharField(max_length=100)),
                ('RecIDPlaceHolder', models.IntegerField(default=-1)),
                ('RecName', models.CharField(max_length=100)),
                ('RecLongtitude', models.FloatField(default=0)),
                ('RecLatitude', models.FloatField(default=0)),
                ('RecPlaceOwner', models.CharField(max_length=100)),
                ('RecPlaceUser', models.CharField(max_length=100)),
                ('RecAltitude', models.FloatField(default=0)),
                ('RecAltitude_Ustie', models.FloatField(default=0)),
                ('RecElevation', models.FloatField(default=0)),
                ('RecType', models.CharField(choices=[('H', 'Горизонтальная'), ('V', 'Вертикальная'), ('N', 'Наклонная')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceHolder',
            fields=[
                ('RecID', models.AutoField(primary_key=True, serialize=False)),
                ('RecName', models.CharField(max_length=50)),
            ],
        ),
    ]
