# Generated by Django 4.2.6 on 2023-11-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_cdictionaryproperty_crock_cwell_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFamily',
            fields=[
                ('RecID', models.AutoField(primary_key=True, serialize=False)),
                ('RecParentFamilyID', models.IntegerField(default=-1)),
                ('RecName', models.CharField(max_length=50)),
                ('RecMin', models.FloatField(default=0, null=True)),
                ('RecMax', models.FloatField(default=0, null=True)),
                ('RecLimitInf', models.FloatField(default=0, null=True)),
                ('RecLimitSup', models.FloatField(default=0, null=True)),
                ('RecScale', models.CharField(max_length=40, null=True)),
                ('RecColorLogview', models.CharField(max_length=40, null=True)),
                ('RecColorTechlog', models.CharField(max_length=40, null=True)),
                ('RecColorTrack', models.CharField(max_length=40, null=True)),
                ('RecType', models.CharField(max_length=40, null=True)),
                ('RecLineType', models.IntegerField(default=0, null=True)),
                ('RecThickness', models.IntegerField(default=0, null=True)),
                ('RecMarkerDisplay', models.CharField(max_length=40, null=True)),
                ('RecMarkerType', models.CharField(max_length=40, null=True)),
                ('RecMarkerSize', models.CharField(max_length=40, null=True)),
                ('RecWrapDisplay', models.CharField(max_length=40, null=True)),
                ('RecWrapFact', models.CharField(max_length=40, null=True)),
                ('RecWrapColor', models.CharField(max_length=40, null=True)),
                ('RecWrapThickness', models.CharField(max_length=40, null=True)),
                ('RecFillType', models.CharField(max_length=40, null=True)),
                ('RecPalette', models.CharField(max_length=40, null=True)),
                ('RecColor1', models.CharField(max_length=40, null=True)),
                ('RecColor2', models.CharField(max_length=40, null=True)),
                ('RecBicolorType', models.CharField(max_length=40, null=True)),
                ('RecFillTo', models.CharField(max_length=40, null=True)),
                ('RecBaselineValue', models.CharField(max_length=40, null=True)),
                ('RecBaselineThickness', models.CharField(max_length=40, null=True)),
                ('RecBaselineColor', models.CharField(max_length=40, null=True)),
                ('RecNbRepetitions', models.CharField(max_length=40, null=True)),
                ('RecNbVerticalLinesOnGrid', models.CharField(max_length=40, null=True)),
                ('RecColorFirstColumn', models.CharField(max_length=40, null=True)),
                ('RecColorLog', models.CharField(max_length=40, null=True)),
                ('RecColorLastColumn', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CParentFamily',
            fields=[
                ('RecID', models.AutoField(primary_key=True, serialize=False)),
                ('RecName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CRockParamValue',
            fields=[
                ('RecID', models.BigAutoField(primary_key=True, serialize=False)),
                ('RecRockResearchID', models.IntegerField(default=-1)),
                ('RecDictionaryPropertyID', models.IntegerField(default=-1)),
                ('RecDepth', models.FloatField(default=-1)),
                ('RecValue', models.FloatField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='CRockResearch',
            fields=[
                ('RecID', models.BigAutoField(primary_key=True, serialize=False)),
                ('RecDT', models.IntegerField(default=-1)),
                ('RecRockID', models.IntegerField(default=-1)),
                ('RecType', models.CharField(choices=[('D', 'DataSet'), ('K', 'Данные по керну'), ('S', 'Стратиграфия'), ('R', 'Траектория')], max_length=1)),
                ('RecName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cdictionaryproperty',
            name='RecFamilyID',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='cdictionaryproperty',
            name='RecUnit',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cdictionaryproperty',
            name='RecSymbols',
            field=models.CharField(max_length=40),
        ),
    ]
