# Generated by Django 4.2.6 on 2023-11-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_cfamily_cparentfamily_crockparamvalue_crockresearch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUploadedFile',
            fields=[
                ('RecID', models.BigAutoField(primary_key=True, serialize=False)),
                ('RevFile', models.FileField(upload_to='')),
                ('RecUploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
