# Generated by Django 4.2.6 on 2023-11-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_cuploadedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuploadedfile',
            old_name='RevFile',
            new_name='RecFile',
        ),
    ]
