# Generated by Django 4.2.6 on 2023-11-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_revfile_cuploadedfile_recfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAllias',
            fields=[
                ('RecID', models.BigAutoField(primary_key=True, serialize=False)),
                ('RecAllias', models.CharField(max_length=100)),
                ('RecTable', models.CharField(max_length=30)),
                ('RecField', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='crockresearch',
            name='RecStep',
            field=models.FloatField(default=-1),
        ),
    ]
