# Generated by Django 4.2.6 on 2023-11-14 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_callias_crockresearch_recstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='crock',
            name='Well',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.cwell'),
            preserve_default=False,
        ),
    ]
