# Generated by Django 4.2.6 on 2023-11-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_crock_well'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crock',
            name='Well',
        ),
    ]
