# Generated by Django 4.2.6 on 2023-12-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_crock_well'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCalculation',
            fields=[
                ('RecID', models.BigAutoField(primary_key=True, serialize=False)),
                ('RecFormula', models.CharField(default='', max_length=100)),
                ('RecFile', models.FileField(upload_to='')),
                ('RecUploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CFormulaVariables',
            fields=[
                ('RecID', models.BigAutoField(primary_key=True, serialize=False)),
                ('RecFormulaID', models.IntegerField(default=-1)),
                ('RecVariable', models.CharField(default='', max_length=100)),
                ('RecDictionaryPropertyID', models.IntegerField(default=-1)),
                ('RecDescription', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
