# Generated by Django 4.2.6 on 2023-12-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_ccalculation_cformulavariables'),
    ]

    operations = [
        migrations.CreateModel(
            name='CZone',
            fields=[
                ('RecID', models.BigAutoField(primary_key=True, serialize=False)),
                ('RecName', models.CharField(default='', max_length=100)),
                ('RecDepthStart', models.FloatField(default=-1)),
                ('RecDepthfinish', models.FloatField(default=-1)),
                ('RecDefaultColor', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ccalculation',
            name='RecFile',
        ),
        migrations.RemoveField(
            model_name='ccalculation',
            name='RecUploaded_on',
        ),
    ]
